Repository Abhigyan103/Clickboard, pull requests merged in 2024-01, with the labels that each got.

#27 Password visibility Fix
  lib/src/core/common_widgets/my_text_field.dart
  lib/src/features/authentication/controllers/auth_controller.dart
  lib/src/features/authentication/screens/login/widgets/login_form.dart
  lib/src/features/authentication/screens/signup/widgets/signup_form.dart
Labels: easy, JWOC

#35 Removed the green background from specified icons
  lib/src/features/profile_screen/screens/widgets/account_list_tile.dart
Labels: easy, JWOC

#38 Clickboard now runs in ios simulators
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
Labels: easy, JWOC

#44 Feat/change password
  lib/route_generator.dart
  lib/src/features/profile_screen/screens/change_password.dart
  lib/src/features/profile_screen/screens/profile.dart
Labels: medium, JWOC

#47 added admin profile image
  assets/images/AbhigyanSingh_admin.png
  assets/images/abhigyan_singh.png
  lib/src/features/profile_screen/screens/about_us.dart
  pubspec.yaml
Labels: easy, JWOC

#64 Feat/delete user google
  lib/src/core/utils/validators/validators.dart
  lib/src/features/profile_screen/screens/profile.dart
Labels: hard, JWOC

#74 Fix/remove web view
  android/app/src/main/AndroidManifest.xml
  lib/src/core/common_widgets/college_logo.dart
  lib/src/features/profile_screen/screens/about_us.dart
  pubspec.yaml
Labels: hard, JWOC

#79 Feat/rename prompt
  lib/src/core/common_widgets/my_bottom_navigation_bar.dart
  lib/src/features/documents/screens/documents.dart
  lib/src/features/documents/screens/widgets/document_page.dart
Labels: medium, JWOC
